import Head from "next/head";
import { motion } from "framer-motion";
import Link from "next/link";
import { InvisibleNavbar } from "@/components/InvisibleNavbar";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-full min-h-screen bg-black font-mono">
				<InvisibleNavbar />
				<div className="mt-5 w-full h-full flex flex-col items-center place-content-center p-3">
					<div className="w-full h-full">
						<img
							src="./assets/home.png"
							className="w-full h-full object-contain"
						/>
					</div>

					<img
						src="./assets/title.png"
						className="absolute w-full max-w-lg sm:max-w-xl md:max-w-2xl lg:max-w-4xl p-3 mt-[150px] sm:mt-[200px] drop-shadow-2xl"
					/>
				</div>

				<div
					className="p-3 flex flex-col items-center content-center text-center w-full text-white 
          drop-shadow-2xl text-md lg:text-2xl font-mono mt-[30px]"
				>
					<div className="mt-[40px] sm:mt-[10px] md:mt-[0px] max-w-xl lg:max-w-4xl leading-5 sm:leading-6 lg:leading-7">
						<b>Messed</b> up QTE / took a <i>wrong</i> decision?{" "}
						<b>TvT</b>
						<br />
						<br />
						<i>Fret{"'"} Not!</i> I created <b>savegames</b> for
						every important decision that follows the best ending (
						<b>everyone</b> lives + <b>12</b> chapter trophies +{" "}
						<b>most</b> collectibles)
						<br />
						<br />
						Just <i>pick</i> the decision where you messed up,&nbsp;
						<b>download</b>&nbsp;savegame and start <b>playing</b>{" "}
						:)
					</div>
					<div className="max-w-4xl italic text-red-600 mt-3 font-bold "></div>

					<Link
						target="_self"
						rel="noopener noreferrer"
						href={{
							pathname: "/savegames",
						}}
					>
						<motion.button
							whileTap={{
								scale: 0.9,
								transition: {
									duration: 0.03,
								},
							}}
							className="mt-4 flex flex-col items-center bg-isRedDarkEmphasis hover:bg-isRedDark
			text-isWhite py-1 px-4 text-lg md:text-xl lg:text-2xl rounded-xl font-black cursor-pointer
			transition duration-300 ease-in-out"
						>
							Click here to start!
						</motion.button>
					</Link>

					<div className="mt-[90px] flex flex-row items-center mb-3">
						created by&nbsp;
						<Link
							target="_blank"
							rel="noopener noreferrer"
							href="https://twitter.com/yupuday"
						>
							<span
								className="bg-isBlueDarkEmphasis hover:bg-isBlueDark px-3 py-1 rounded-xl font-black
							transition duration-300 ease-in-out"
							>
								<b>@yupuday</b>
							</span>
						</Link>
					</div>
				</div>
			</main>
		</>
	);
}
