import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import HomeImage from "../public/assets/home.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-full min-h-screen bg-black">
				<div className="w-full h-full flex flex-col items-center place-content-center p-3">
					<div className="w-full h-full">
						<img
							src="./assets/home.png"
							className="w-full h-full object-contain"
						/>
					</div>

					<img
						src="./assets/title.png"
						className="absolute w-full max-w-lg sm:max-w-xl md:max-w-2xl lg:max-w-4xl p-3 mt-[150px] sm:mt-[200px] drop-shadow-2xl"
					/>
				</div>

				<div
					className="p-3 flex flex-col items-center content-center text-center w-full text-white 
          drop-shadow-2xl text-md lg:text-2xl font-medium "
				>
					<div className="mt-[40px] sm:mt-[10px] md:mt-[0px] max-w-xl lg:max-w-4xl leading-5 sm:leading-6 lg:leading-7">
						We got <b>all</b> save game files for <i>every fking</i>{" "}
						decision to get that perfect ending --{" "}
						<b>
							everyone lives + tarot cards + collectible trophies.
						</b>{" "}
						<br />
					</div>
					<div className="max-w-4xl italic text-red-600 mt-3 font-bold "></div>
				</div>

				<div className="p-3 flex flex-col w-full items-center">
					<div className="grid grid-cols-4 max-w-5xl">
						<div
							className="font-mono flex flex-col items-center w-full bg-stone-500 text-xl text-center rounded-lg py-[3px] px-[12px]
            font-semibold text-slate-200 "
						>
							Select Savegame
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
